apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: spring-boot-app
        image: jilla5858/javasampleapp:latest
        ports:
        - containerPort: 8080
      imagePullPolicy: Always
          
